[project]
name = "analyse-pyspark"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.8",
    "pandas>=3.0.0",
    "pyspark>=3.5.0,<4.0.0",
    "seaborn>=0.13.2",
]
